server:
  port: 8700

logging:
  level:
    root: INFO
    org:
      springframework: INFO
      postgresql.Driver: INFO
      hibernate.SQL: INFO

spring:
  application.name: "crypto-tracker"
  config:
    import: vault://
  cloud:
    vault:
      token: ${VAULT_TOKEN}
      uri: ${VAULT_URI}
      kv:
        enabled: true
        default-context: 'crypto-tracker'
  datasource:
    hikari:
      maximumPoolSize: 10
    driver-class-name: org.postgresql.Driver
  jackson:
    default-property-inclusion: non_empty
  jpa:
    open-in-view: true
    properties:
      hibernate:
        jdbc.time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
      temp:
        use_jdbc_metadata_defaults: false
    hibernate:
      connection:
        provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      show-sql: true
  liquibase:
    change-log: classpath:db/changelog-master.yml

springdoc:
  swagger-ui:
    path: /swagger-ui.html

coinMarket:
  api:
    url: ${crypto-api.url}
    key: ${crypto-api.key}
  saved-cryptos:
    start: 1
    end: 200
