name: Build-app-workflow

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    name: Build-app
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: 25
          distribution: 'temurin'
          cache: 'maven'
      - name: Maven Package
        run: mvn -B clean package

  sonar:
    name: Sonar-cloud
    runs-on: ubuntu-latest
    needs: [ build ]
    timeout-minutes: 20
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: 25
          distribution: 'temurin'
          cache: 'maven'
      - name: SonarCloud Scan
        if: ${{ env.SONAR_TOKEN != '' }}
        run: mvn -B clean verify -Psonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
