name: Develop workflow

on:
  push:
    branches:
      - develop

concurrency:
  group: dev-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  buildAndSonar:
    name: Build-app
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy-artifact:
    name: Deploy-artifact
    needs: [ buildAndSonar ]
    permissions:
      contents: write
      packages: write
    uses: ./.github/workflows/deploy-artifact.yml
    secrets: inherit

  build-docker-latest:
    name: Build-docker-latest
    needs: [ buildAndSonar ]
    uses: ./.github/workflows/build-docker.yml
    with:
      version: false
    secrets: inherit
