name: Branch Others workflow

on:
  push:
    branches-ignore:
      - develop
      - master

concurrency:
  group: others-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
jobs:
  buildAndSonar:
    name: Build-app
    uses: ./.github/workflows/build.yml
    secrets: inherit

  build-docker-branch:
    name: Build-docker-branch
    needs: [ buildAndSonar ]
    uses: ./.github/workflows/build-docker.yml
    with:
      version: false
    secrets: inherit
