name: Branch PullRequest workflow

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions:
  actions: write
jobs:
  buildAndSonar:
    name: Build-app
    uses: ./.github/workflows/build.yml
    secrets: inherit
