name: Branch PullRequest workflow

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions:
  actions: write
jobs:
  buildAndSonar:
    name: Build-app
    runs-on: ubuntu-latest
    steps:
      - name: build_sonar_ext
        uses: aurelien-baudet/workflow-dispatch@v2.1.1
        with:
          workflow: Build-app-workflow
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}
          display-workflow-run-url: true
          display-workflow-run-url-timeout: 10m
          display-workflow-run-url-interval: 15s
          wait-for-completion-timeout: 10m
          wait-for-completion-interval: 15s
