name: Release workflow

on:
  push:
    tags:
      - 'crypto-tracker-*.*.*'

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  buildAndSonar:
    name: Build-app
    uses: ./.github/workflows/build.yml
    secrets: inherit

  build-docker-version:
    name: Build-docker-version
    needs: [ buildAndSonar ]
    uses: ./.github/workflows/build-docker.yml
    with:
      version: true
    secrets: inherit
